#vim: set ft=ansible:
---
- name: install openshift_node packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - vim
      - tmux
      - ntp
      - bash-completion
      # - wget
      # - git
      # - net-tools
      # - bind-utils
      # - iptables-services
      # - bridge-utils
      # - yum-versionlock
      # - httpd-tools
      # - sysstat
      # - strace
      # - tcpdump
  tags:
   - install_openshift_node_packages
