#vim: set ft=ansible:
---
######################### Install Basic Packages
- name: install basic packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{common_packages}}"
  register: yumr
  until: yumr is succeeded
  any_errors_fatal: true
  fork: 20
  tags:
    - install_common_packages
