---
- name: Step 001.1 Deploy Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  # vars_files:
  #   - ".//configs/{{ env_type }}/env_vars.yml"
  #   - ".//configs/{{ env_type }}/env_secret_vars.yml"
  tags:
    - step001
    - step001.1
    - deploy_infrastructure
  tasks:
    - name: Run infra-ec2-template-generate Role
      import_role:
        name: ".//roles/infra-ec2-template-generate"

    - name: Run infra-ec2-template-create Role
      import_role:
        name: ".//roles/infra-ec2-template-create"
      vars:
        aws_region_loop: "{{aws_region}}"
